export default function getAllProducts() {
  return [
    {
      id: "nasgor",
      slug: "nasgor",
      name: "Nasi Goreng Ayam",
      category: "Makanan Berat",
      categorySlug: "makanan-berat",
      price: 25_000,
      stock: 100,
      imageUrl: "/assets/images/NasiGorengAyam.jpg",
      description: `Nasi goreng ayam yang sangat enak adalah hidangan khas yang memikat selera dengan aroma harum rempah-rempah dan ayam yang gurih. Potongan ayam yang lembut dan juicy menambah kelezatan tiap suapan, berpadu dengan nasi yang bertekstur ringan namun tidak lembek. Ditambah sedikit taburan daun bawang dan bawang goreng yang renyah di atasnya, serta acar segar dan telur mata sapi di sampingnya, membuat nasi goreng ayam ini semakin sempurna dan sulit untuk ditolak.`,
    },
    {
      id: "sate",
      slug: "sate",
      name: "Sate Ayam",
      category: "Makanan Berat",
      categorySlug: "makanan-berat",
      price: 20_000,
      stock: 5,
      imageUrl: `/assets/images/SateAyam.jpg`,
      description: `Sate ayam yang sangat lezat adalah sajian khas yang memanjakan lidah dengan perpaduan rasa manis, gurih, dan sedikit smoky dari proses pembakaran. Daging ayam dipotong kecil-kecil, lalu direndam dalam bumbu sederhana yang terbuat dari bawang putih, ketumbar, dan sedikit kecap manis untuk menghasilkan rasa yang meresap sempurna.`,
    },
    {
      id: "marlur",
      slug: "marlur",
      name: "Martabak Telor",
      category: "Makanan Ringan",
      categorySlug: "makanan-ringan",
      price: 30_000,
      stock: 0,
      imageUrl: `/assets/images/MartabakTelot.jpg`,
      description: `Martabak telor yang lezat adalah camilan gurih yang dibuat dari adonan tipis, renyah di luar namun lembut di dalam. Isiannya terdiri dari campuran telur, daging cincang (biasanya daging sapi atau ayam), daun bawang, dan bumbu seperti bawang putih, merica, serta sedikit garam, yang menghasilkan rasa gurih sempurna.`,
    },
    {
      id: "terbul",
      slug: "terangbulan",
      name: "Terang Bulan",
      category: "Makanan Ringan",
      categorySlug: "makanan-ringan",
      price: 35_000,
      stock: 30,
      imageUrl: `/assets/images/TerangBulan.jpg`,
      description: `Terang bulan yang nikmat adalah kudapan manis dengan tekstur lembut dan kenyal di bagian dalam, serta sedikit renyah di bagian tepinya. terang bulan pilihan yang sempurna untuk camilan atau sebagai makanan penutup yang memuaskan.`,
    },
    {
      id: "migor",
      slug: "miegoreng",
      name: "Mie Goreng",
      category: "Makanan Berat",
      categorySlug: "makanan-berat",
      price: 15_000,
      stock: 10,
      imageUrl: `/assets/images/MieGoreng.jpg`,
      description: `Terang bulan yang nikmat adalah kudapan manis dengan tekstur lembut dan kenyal di bagian dalam, serta sedikit renyah di bagian tepinya. terang bulan pilihan yang sempurna untuk camilan atau sebagai makanan penutup yang memuaskan.`,
    },
  ];
}
